//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.25 at 05:46:24 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.simplex-software.fr/money-transfer", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.simplex_software.bank.money_transfer.jaxb;
